# Generated by Django 5.0.2 on 2024-02-18 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0005_remove_employeeuser_emailid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internuser',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
        migrations.AddField(
            model_name='internuser',
            name='phone',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ems_app.domain'),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ems_app.domain'),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
