# Generated by Django 5.0.2 on 2024-02-18 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0006_internuser_email_internuser_phone_alter_domain_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internuser',
            name='domain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems_app.domain'),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
