# Generated by Django 5.0.2 on 2024-02-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0007_alter_internuser_domain_alter_internuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internuser',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ems_app.domain'),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
