# Generated by Django 5.0.2 on 2024-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0008_alter_internuser_domain_alter_internuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='domain',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='phone',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
