# Generated by Django 5.0.2 on 2024-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0010_module_topic_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images/'),
        ),
        migrations.AddField(
            model_name='module',
            name='question',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='topic',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
