# Generated by Django 5.0.2 on 2024-02-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0011_remove_topic_module_module_image_module_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
