# Generated by Django 5.0.2 on 2024-02-20 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0012_alter_module_question_alter_module_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employeeuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
