# Generated by Django 5.0.2 on 2024-02-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0019_alter_internanswer_intern_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internuser',
            old_name='name',
            new_name='username',
        ),
    ]
